places = [ 'lanzhou','beijing','shenzhen','nanjing','chengdu' ];
print(places);
print(sorted(places));
print(places);
print('========================================================');
print(sorted(places,reverse=True));
print(places);
print('========================================================');
places.reverse();
print(places);
places.reverse();
print(places);
places.sort();
print(places);
places.sort(reverse=True);
print(places);
